### PR TITLE
docker: define client cert auth env variables

### PR DESCRIPTION
**Pull request by guusdk**
4e18ee1b268447ce1ba262ff4048536401b6f5b7 adds support for client cert authentication.

With this support, a couple of new environment variables need to be defined. Without them,
`docker-compose up` complains.

```
xmpp_1         | Traceback (most recent call last):
xmpp_1         |   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
xmpp_1         |     return _run_code(code, main_globals, None,
xmpp_1         |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
xmpp_1         |     exec(code, run_globals)
xmpp_1         |   File "/usr/local/lib/python3.9/dist-packages/testxmpp/xmpp/__main__.py", line 2, in <module>
xmpp_1         |     testxmpp.xmpp.cli.main()
xmpp_1         |   File "/usr/local/lib/python3.9/dist-packages/testxmpp/xmpp/cli.py", line 60, in main
xmpp_1         |     config = environ.to_config(AppConfig)
xmpp_1         |   File "/usr/local/lib/python3.9/dist-packages/environ/_environ_config.py", line 218, in to_config
xmpp_1         |     return _to_config(config_cls, default_get, environ, ())
xmpp_1         |   File "/usr/local/lib/python3.9/dist-packages/environ/_environ_config.py", line 230, in _to_config
xmpp_1         |     val = get(environ, a.metadata, prefix, a.name)
xmpp_1         |   File "/usr/local/lib/python3.9/dist-packages/environ/_environ_config.py", line 215, in default_get
xmpp_1         |     raise MissingEnvValueError(var)
xmpp_1         | environ.exceptions.MissingEnvValueError: TESTXMPP_S2S_CLIENT_CERT
```

### CODE REVIEW

**Comment by horazont** [comment]
@guusdk Hm, I'm not sure if it makes sense to set invalid values -- they will cause problems down the road, possibly while setting up the SSL context. I'd prefer to fail early. Or have you observed that things work despite them being set to the empty string? (If so, I'll have to go and curse openssl)

**Comment by guusdk** [comment]
My primary reason for this change was that I _thought_ it prevented the web interface from launching, which turned out to be false assumption (instead, the web interface launched on a [different port](https://github.com/horazont/testxmpp/pull/5) than the one documented, which I didn't notice until after finding out that this PR didn't make the web interface available). So, the added value of this PR might be very, very low.

With these invalid environment values added, I _was_ able to launch a s2s check that gave some results that at first glance seemed ... ok? That likely did not use mutual authentication (which is what I think is what these new variables configure)?

**Comment by horazont** [comment]
Hm, concerning. I would've expected OpenSSL to error out.

The client certificates are not *generally* required. Some deployments (those which run without dialback and with requirement for s2s auth) may require a client certificate to even accept a connection, hence they are required in that situation.

As the checker will emit weird errors when the certificates are absent, I probably should handle that case better -- but I don't think that defaulting the variables to values which will not work in such cases is a good solution here.

**Comment by guusdk** [comment]
I strongly do not disagree.

**Comment by guusdk** [comment]
For posterity: after 28 days, we discovered that while I was coming from a c2s perspective, @horazont was thinking s2s.
Client-sided certs are a lot more common in s2s than they are in c2s.

**Pull request closed without merging**
